govuk-one-login/ipv-cri-bav-api

.github/CODEOWNERS
.github/pull_request_template.md
.gitignore
.pre-commit-config.yaml

- Created a new repository for BAV CRI.
- Set up initial configuration for the BAV CRI frontend.

KIWI-1252: Initial configuration for new BAV CRI backend

---

.secrets.baseline

- Set up the secrets baseline as a part of initial configuration
- [KIWI-1252](https://govukverify.atlassian.net/browse/KIWI-1252)
[KIWI-1252]: https://govukverify.atlassian.net/browse/KIWI-1252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KIWI-1252: Setup Secrets baselline

---

.github/workflows/post-merge-kms-build.yml
.github/workflows/post-merge-kms-dev.yml
.github/workflows/pull-request-KMS.yml
infra-l2-kms/.gitignore
infra-l2-kms/jest.config.ts
infra-l2-kms/package-lock.json
infra-l2-kms/package.json
infra-l2-kms/src/tests/infra/infra.test.ts
infra-l2-kms/template.yaml
infra-l2-kms/tsconfig.json

- Create Layer 2 stack for BAV CRI KMS
- [KIWI-1181](https://govukverify.atlassian.net/browse/KIWI-1181)
[KIWI-1181]: https://govukverify.atlassian.net/browse/KIWI-1181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KIWI-1181: Create layer 2 stack for BAV CRI KMS

---

.github/workflows/post-merge-dynamo-to-build.yml
.github/workflows/post-merge-dynamo-to-dev.yml
.github/workflows/pull-request-Dynamo.yml
infra-l2-dynamo/.gitignore
infra-l2-dynamo/jest.config.ts
infra-l2-dynamo/package-lock.json
infra-l2-dynamo/package.json
infra-l2-dynamo/src/tests/infra/infra.test.ts
infra-l2-dynamo/template.yaml
infra-l2-dynamo/tsconfig.json

- Create layer 2 stack for the DynamoDB
- [KIWI-1182](https://govukverify.atlassian.net/browse/KIWI-1182)
[KIWI-1182]: https://govukverify.atlassian.net/browse/KIWI-1182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Kiwi-1180: Create Layer 2 stack for the BAV CRI DynamoDB

---

deploy/bav-spec.yaml
deploy/template.yaml

Adds BAV template and spec
Needed for other tickets
Deploys successfully
- [KIWI-1289](https://govukverify.atlassian.net/browse/KIWI-1289)
[KIWI-1289]: https://govukverify.atlassian.net/browse/KIWI-1289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KIWI-1289 template

---

.github/workflows/post-merge-push-test-container-to-build.yml
.github/workflows/post-merge-push-test-container-to-dev.yml

- Create a workflow to creates test container for dev and build enviroments
This process should be done through a workflow to avoid manual intervention.
- [KIWI-1406](https://govukverify.atlassian.net/browse/KIWI-1406)
[KIWI-1406]: https://govukverify.atlassian.net/browse/KIWI-1406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KIWI-1406: Deploy test container to dev and build environments

---

deploy/template.yaml

Update expected ClientID for IPV in Build

[KIWI-1464] - Fix ClientID in Build Env for IPVStub

---

deploy/template.yaml

Update the jwksEndpoint for Build

Fix Client jwksEndpoint

---

deploy/template.yaml

Updating TESTHARNESSURL for Build

Updating TESTHARNESSURL for Build

---

deploy/template.yaml

Add environment variables to deploy on integration and production
- [KIWI-1447](https://govukverify.atlassian.net/browse/KIWI-1447)
[KIWI-1447]: https://govukverify.atlassian.net/browse/KIWI-1447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KIWI-1447: Integration in Higher environments

---

src/tests/api/BavHappyPath.test.ts
src/tests/api/BavUnhappyPath.test.ts
src/tests/utils/ApiTestSteps.ts

Added all happy and unhappy tests for the /abort endpoint
- [KIWI-1378](https://govukverify.atlassian.net/browse/KIWI-1378)
[KIWI-1378]: https://govukverify.atlassian.net/browse/KIWI-1378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KIWI 1378 QA

---

deploy/template.yaml

Integrate Dynatrace Lambda layer into Lambda function to ingest metrics in Dynatrace to allow for application level monitoring for OneLogin
Enable Lambda metrics in Dynatrace
- [KIWI-1467](https://govukverify.atlassian.net/browse/KIWI-1467)
[KIWI-1467]: https://govukverify.atlassian.net/browse/KIWI-1467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[KIWI-1467] Enable Lambda metrics in Dynatrace

---

src/tests/data/BAV_CRI_END_SCHEMA.json
src/tests/data/BAV_CRI_SESSION_ABORTED_SCHEMA.json
src/tests/data/BAV_CRI_START_SCHEMA.json
src/tests/data/BAV_CRI_VC_ISSUED_SCHEMA.json
src/tests/utils/ApiTestSteps.ts

TxMA Tests will now properly fail when the related JSON schema is missing.
- [KIWI-1494](https://govukverify.atlassian.net/browse/KIWI-1494)
[KIWI-1494]: https://govukverify.atlassian.net/browse/KIWI-1494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KIWI 1494 QA

---

src/tests/api/BavHappyPath.test.ts
src/tests/api/BavUnhappyPath.test.ts

Automated tests for KIWI-1416
Name retry logic to be added as part of dev PR, QA changes needed
- [KIWI-1416](https://govukverify.atlassian.net/browse/KIWI-1416)
[KIWI-1416]: https://govukverify.atlassian.net/browse/KIWI-1416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KIWI-1416 QA Updates

---

src/package-lock.json
src/package.json
src/tests/api/BavHappyPath.test.ts
src/tests/api/BavUnhappyPath.test.ts
src/tests/utils/ApiTestSteps.ts

/person-info QA updates
Test /person-info + /person-info-key endpoints
- [KIWI-1504](https://govukverify.atlassian.net/browse/KIWI-1504)
[KIWI-1504]: https://govukverify.atlassian.net/browse/KIWI-1504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KIWI-1504 QA

---

src/tests/api/BavHappyPath.test.ts
src/tests/data/BAV_COP_REQUEST_SENT_SCHEMA.json
src/tests/data/BAV_COP_RESPONSE_RECEIVED_SCHEMA.json
src/tests/data/BAV_CRI_START_SCHEMA.json

Added 2 new schemas and the relevant validation for them.
- [KIWI-1431](https://govukverify.atlassian.net/browse/KIWI-1431)
- [KIWI-1520](https://govukverify.atlassian.net/browse/KIWI-1520)
[KIWI-1431]: https://govukverify.atlassian.net/browse/KIWI-1431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KIWI-1520]: https://govukverify.atlassian.net/browse/KIWI-1520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KIWI 1520 QA

---

src/tests/api/BavHappyPath.test.ts
src/tests/data/BAV_CRI_VC_ISSUED_SCHEMA.json

Amended the CRI_VC_ISSUED schema to reflect the new changes and fixed a TxMA validation test for /verify-account endpoint.
- [KIWI-1431](https://govukverify.atlassian.net/browse/KIWI-1431)
- [KIWI-1523](https://govukverify.atlassian.net/browse/KIWI-1523)
[KIWI-1431]: https://govukverify.atlassian.net/browse/KIWI-1431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KIWI-1523]: https://govukverify.atlassian.net/browse/KIWI-1523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KIWI 1523 QA

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml
README.md

- Added pre-commit workflow
- Updated pre-commit hooks
- Updated readme
- Align with other repos across identity pod
- General housekeeping
- [IPS-484](https://govukverify.atlassian.net/browse/IPS-484)
[IPS-484]: https://govukverify.atlassian.net/browse/IPS-484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-486: Add pre-commit

---

deploy/template.yaml

Added conditional logic to `POWERTOOLS_LOG_LEVEL` dependent on environment.
- [KIWI-1611](https://govukverify.atlassian.net/browse/KIWI-1611)
[KIWI-1611]: https://govukverify.atlassian.net/browse/KIWI-1611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[KIWI-1611] - BAV | BE | Limit logs in prod to INFO and higher

---

src/tests/data/BAV_COP_REQUEST_SENT_SCHEMA.json
src/tests/data/BAV_COP_RESPONSE_RECEIVED_SCHEMA.json
src/tests/data/BAV_CRI_END_SCHEMA.json
src/tests/data/BAV_CRI_SESSION_ABORTED_SCHEMA.json
src/tests/data/BAV_CRI_START_SCHEMA.json
src/tests/data/BAV_CRI_VC_ISSUED_SCHEMA.json

BE Stack: f2f-cri-api-1626
Test Results: 
Add event_timestamp_ms to JSON Schema for TxMA checks
- [KIWI-1626](https://govukverify.atlassian.net/browse/KIWI-1626)
[KIWI-1626]: https://govukverify.atlassian.net/browse/KIWI-1626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KIWI-1626 QA Updates

---

test-harness/test-harness-spec.yaml

Update Test Harness spec to get session record by auth code
Support E2E testing and allow us to run BE validation following a FE journey
- [KIWI-1672](https://govukverify.atlassian.net/browse/KIWI-1672)
[KIWI-1672]: https://govukverify.atlassian.net/browse/KIWI-1672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update Test Harness spec to get session record by auth code

---

bav-ipv-stub/src/handlers/startBavCheck.ts

Pass custom frontend URL to IPV Stub

[KIWI-1559] - Enable use of custom frontend urls

---

deploy/template.yaml
run-tests.sh
src/tests/api/BavHappyPath.test.ts
src/tests/utils/ApiConstants.ts
src/tests/utils/ApiTestSteps.ts

- [KIWI-1590](https://govukverify.atlassian.net/browse/KIWI-1590)
[KIWI-1590]: https://govukverify.atlassian.net/browse/KIWI-1590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KIWI-1590-QA Updates

---

src/check-logs.sh

Updates to query for script to check for PII data in logs
Update the PII script to reflect changes in Test Data
- [KIWI-1712](https://govukverify.atlassian.net/browse/KIWI-1712)
[KIWI-1712]: https://govukverify.atlassian.net/browse/KIWI-1712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update query for script to check for PII data in logs

---

deploy/template.yaml

[KIWI-1640] Updating TTL in dev to 1 day

---

run-tests-locally.sh
run-tests.sh

Update run-tests logic to output report for failed test runs
Store report for failed runs in CodeBuild
- [KIWI-1685](https://govukverify.atlassian.net/browse/KIWI-1685)
[KIWI-1685]: https://govukverify.atlassian.net/browse/KIWI-1685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KIWI-1685 QA BAV

---

src/services/VerifiableCredentialService.ts

Add URN_UUID_PREFIX to jti in BAV VC

[KIWI-1777] Add URN_UUID_PREFIX to jti in BAV VC

---

src/services/BavService.ts
src/tests/unit/services/BavService.test.ts

Only include encoded TxMA header if not empty

[KIWI-1771] - Only include encoded TxMA header if not empty

---

deploy/template.yaml

- [KIWI-1473](https://govukverify.atlassian.net/browse/KIWI-1473)
[KIWI-1473]: https://govukverify.atlassian.net/browse/KIWI-1473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KIWI-1473 | Managed Policy for Athena Query Role

---

deploy/samconfig.toml
deploy/template.yaml

AccessLogSetting changed to include more detailed information that is needed for alarms
- [KIWI-1812](https://govukverify.atlassian.net/browse/KIWI-1812)
[KIWI-1812]: https://govukverify.atlassian.net/browse/KIWI-1812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KIWI-1812: Updates the AccessLogSetting

---

deploy/template.yaml

Reverting the CF template changes to fix the build.

[KIWI-1841]Revert 1841 code change

---

devutils/README.md
devutils/deleteBucket.sh
devutils/deleteStack.sh

Creates a new script for use by devs to cleanly delete cloudformation stacks

Create new script to cleanly delete cloudformation stack

---

.github/workflows/post-merge-dynamo-to-build.yml
.github/workflows/post-merge-dynamo-to-dev.yml
.github/workflows/post-merge-ipv-stub-package-to-build.yml
.github/workflows/post-merge-ipv-stub-package-to-dev.yml
.github/workflows/post-merge-kms-build.yml
.github/workflows/post-merge-kms-dev.yml
.github/workflows/post-merge-outbound-proxy-to-build.yml
.github/workflows/post-merge-outbound-proxy-to-dev.yml
.github/workflows/post-merge-package-to-build.yml
.github/workflows/post-merge-package-to-dev.yml
.github/workflows/post-merge-test-harness-package-to-build.yml
.github/workflows/post-merge-test-harness-package-to-dev.yml

- Update upload action version v3 to v3.8.1
- Update the sam build template path
- Update upload action version v3 to v3.8.1 and add the full sam build path
- [IPS-814](https://govukverify.atlassian.net/browse/IPS-814)
[IPS-814]: https://govukverify.atlassian.net/browse/IPS-814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-814: Update Upload action version

---

.github/workflows/post-merge-dynamo-to-build.yml
.github/workflows/post-merge-dynamo-to-dev.yml
.github/workflows/post-merge-ipv-stub-package-to-build.yml
.github/workflows/post-merge-ipv-stub-package-to-dev.yml
.github/workflows/post-merge-kms-build.yml
.github/workflows/post-merge-kms-dev.yml
.github/workflows/post-merge-outbound-proxy-to-build.yml
.github/workflows/post-merge-outbound-proxy-to-dev.yml
.github/workflows/post-merge-test-harness-package-to-build.yml
.github/workflows/post-merge-test-harness-package-to-dev.yml

- Add workflow yaml file to the paths to for changes to apply
- Add workflow yaml file to the paths to for changes to apply
- Previous merged without workflow applying changes
- [IPS-814](https://govukverify.atlassian.net/browse/IPS-814)
[IPS-814]: https://govukverify.atlassian.net/browse/IPS-814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-814: Add workflow yaml file for changes to apply

---

bav-ipv-stub/package.json
bav-ipv-stub/src/tests/infrastructure.test.ts
infra-l2-dynamo/package.json
infra-l2-dynamo/src/tests/infra/infra.test.ts
infra-l2-kms/package.json
infra-l2-kms/src/tests/infra/infra.test.ts
infra-l2-outbound-proxy/package.json
infra-l2-outbound-proxy/src/lib/test-helper.ts
infra-l2-outbound-proxy/src/tests/infra/infra.test.ts
src/package-lock.json
src/package.json
src/tests/infra/template.test.ts

Migrate from AWS CDK v1 to AWS CDK v2
To address vulnerabilities

BAV | BE | Migrate from AWS CDK v1 to AWS CDK v2

---

deploy/template.yaml

BAV service provider removed

---

deploy/samconfig.toml
deploy/template.yaml
src/tests/infra/template.test.ts

[ KIWI-1872 ] Set AWS CloudWatch log retention to 30 days
Updated the CloudFormation template to set the retention period for all CloudWatch log groups to 30 days (1 month)
Modified the EnvironmentConfiguration mapping in the template to ensure consistent 30-day retention across all environments (dev, build, staging, integration, production)
Applied the change to all Lambda function and API Gateway log groups associated with the BAV API stack
To standardise log retention periods across all environments
To ensure compliance with data retention policies
Issue tracking
[INCIDEN-627](https://govukverify.atlassian.net/browse/INCIDEN-627?focusedCommentId=125675)
- [ CRI-BAV-FRONT ](https://github.com/govuk-one-login/ipv-cri-bav-front/pull/322)
- [ CRI-CIC-FRONT …

[KIWI-1872] - Set AWS CloudWatch log retention to 30 days

---

src/tests/api/ApiTestSteps.ts
src/tests/api/ApiUtils.ts
src/tests/api/backend/BavHappyPath.test.ts
src/tests/api/backend/BavUnhappyPath.test.ts
src/tests/data/BAV_CRI_VC_ISSUED_SCHEMA.json
src/tests/data/BAV_EXPERIAN_REQUEST_SENT.json
src/tests/data/BAV_EXPERIAN_RESPONSE_RECEIVED.json
src/tests/data/bankDetailsYes.json
src/utils/TxmaEvent.ts

Updates to test logic for Experian Stub
BAV service is now pointing to Experian Crosscore third-party stub so test data and scenarios need to be updated to reflect this. 
- [KIWI-1951](https://govukverify.atlassian.net/browse/KIWI-1951)
[KIWI-1951]: https://govukverify.atlassian.net/browse/KIWI-1951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updates to test logic for Experian Stub

---

deploy/template.yaml

Update CF deployment template to point to staging stub

[KIWI-1951] - Template fix

---

deploy/template.yaml

Update CF template to point to Experian URL
To test the 3rd party integration

[KIWI-1925] - Template update

---

src/services/ExperianService.ts
src/tests/unit/services/ExperianService.test.ts

Added additional logging
To assist in triaging the third party connection

KIWI-1960: Adding additional logging to the service

---

.secrets.baseline
src/services/ExperianService.ts
src/tests/unit/services/ExperianService.test.ts

Payload update
Attempting integrate with Experian service

Kiwi 1960d

---

src/tests/data/BAV_CRI_VC_ISSUED_SCHEMA.json

Update structure of successful VC schema
- [KIWI-XXXX](https://govukverify.atlassian.net/browse/KIWI-XXXX)

Update structure of successful VC schema

---

deploy/template.yaml

Reverts govuk-one-login/ipv-cri-bav-api#287

Revert "BAU - NotCreateProdResource condition created"

---

src/services/BavService.ts
src/services/ExperianService.ts
src/services/VerifyAccountRequestProcessor.ts
src/tests/unit/services/ExperianService.test.ts
src/utils/LogResponseCode.ts

Added additional checks for the presence of decision elements
Added additional logging for overall response elements.
Ensure absence of scores is allowed
To facilitate better logging in higher envs.
Allow failure cases to be managed.

KIWI-1960: Added some additional logging and conditions to ensure we are correctly capturing non present fields

---

.secrets.baseline
src/services/VerifyAccountRequestProcessor.ts
src/tests/unit/services/VerifyAccountRequestProcessorExperian.test.ts

Added additional logic to score calculator
To differentiate between failure codes and expected error codes

Live-Proving-fix: Fixed issue where some warning and error codes were incorrectly triggering a failed response

---

.secrets.baseline
src/services/ExperianService.ts
src/services/VerifyAccountRequestProcessor.ts
src/tests/unit/services/ExperianService.test.ts
src/utils/LogResponseCode.ts

Added additional cloudwatch metrics.
To make the BAV outcomes easier to monitor and track

KIWI-2079: Adding additional metrics to make BAV outcomes easier to track

---

.github/workflows/post-merge-push-test-container-to-build.yml
.github/workflows/post-merge-push-test-container-to-dev.yml
traffic-tests/Dockerfile
traffic-tests/run-tests.sh

- Create new container and workflow for Traffic test image
- Create new container and workflow for Traffic test image
- Create new container and workflow for Traffic test image
- [IPS-1242](https://govukverify.atlassian.net/browse/IPS-1242)
[IPS-1242]: https://govukverify.atlassian.net/browse/IPS-1242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-1242: Create new container and workflow for Traffic test image

---

.github/workflows/pull-request-sonar.yml
deploy/template.yaml
src/tests/infra/template.test.ts

This is moving to central firewall management via FMS 
Added tags to tell FMS to use a custom webACL for this resource
Added tags
to tell FMS to use a custom webACL for this resource
https://govukverify.atlassian.net/browse/IPS-1407

Update to include a custom FMS policy

---

deploy/template.yaml

This is now managed centrally via FMS

Remove the REST API WAF as it's in FMS

---

deploy/template.yaml

Reverts govuk-one-login/ipv-cri-bav-api#330

Revert "Remove the REST API WAF as it's in FMS"

---

deploy/template.yaml

This is now managed centrally via FMS

Remove the REST API WAF from Dev as it's in FMS

---

deploy/template.yaml

Putting back the association with WAF for the API

Revert the removing of the WAF association

---

src/tests/api/backend/BavHappyPath.test.ts

Update Test Descriptions for better readability
Retro Action

Update Test Descriptions for better readability

---

src/package-lock.json
src/tests/api/ApiTestSteps.ts
src/tests/api/backend/BavUnhappyPath.test.ts
src/tests/api/types.ts

Added tests for invalidKid + missingKid to BavUnhappyPath test file. 
Negative testing: Key Rotation (BAV)
- [KIWI-2206](https://govukverify.atlassian.net/browse/KIWI-2206)
[KIWI-2206]: https://govukverify.atlassian.net/browse/KIWI-2206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KIWI-2206: BAV Key Rotation QA Updates

---

src/tests/api/ApiConstants.ts
src/tests/api/ApiTestSteps.ts
src/tests/api/alarms/BavAlarms.test.ts
src/tests/api/backend/BavHappyPath.test.ts
src/tests/api/backend/BavUnhappyPath.test.ts
src/tests/api/types.ts
src/tests/unit/data/accessToken-events.ts
src/type/AccessRequestPayload.ts
src/utils/AccessTokenRequestValidations.ts
src/utils/Constants.ts

Add test logic and test cases to validate /token core consumption updates
- [KIWI-2297](https://govukverify.atlassian.net/browse/KIWI-2297)
[KIWI-2297]: https://govukverify.atlassian.net/browse/KIWI-2297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KIWI-2297: BAV /token endpoint Core Consumption QA

---

bav-ipv-stub/src/package-lock.json
bav-ipv-stub/src/package.json
src/package-lock.json
src/package.json

Override `form-data` version
- [KIWI-2412](https://govukverify.atlassian.net/browse/KIWI-2412)
[KIWI-2412]: https://govukverify.atlassian.net/browse/KIWI-2412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KIWI-2412 - Address critical vulnerability in transitive dependency form-data
