- .github/CODEOWNERS
- src/package.json
- Add the CODEOWNERS for new govuk-one-login github BAV API
- Modified the urls pointing to alphagov github repository
- [KIWI-1323](https://govukverify.atlassian.net/browse/KIWI-1323)
[KIWI-1323]: https://govukverify.atlassian.net/browse/KIWI-1323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Github migration - post clean up for BAV CRIbackend

- .github/workflows/pull-request-sonar.yml
- sonar-project.properties
- Create a BAV CRI API workspace on sonar cloud
- Add SONAR_TOKEN on github repo secrets
- Create properties and workflows for sonar
- [KIWI-1262](https://govukverify.atlassian.net/browse/KIWI-1262)
[KIWI-1262]: https://govukverify.atlassian.net/browse/KIWI-1262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1262: Add BAV CRI Api repos on Sonar

- src/tests/api/BavHappyPath.test.ts
- src/tests/api/BavUnhappyPath.test.ts
- src/tests/data/BAV_CRI_AUTH_CODE_ISSUED_SCHEMA.json
Creation of Authorisation Happy and Unhappy Path tests for BAV API
Add Happy and Unhappy path tests to test the /authorisation end point
KIWI-1256 (https://govukverify.atlassian.net/browse/KIWI-1256)
> Kiwi 1256 QA Authorisation tests

- src/package-lock.json
- src/package.json
- src/services/AccessTokenRequestProcessor.ts
- src/tests/api/BavHappyPath.test.ts
- src/tests/api/BavUnhappyPath.test.ts
- src/tests/unit/JwksHandler.test.ts
- src/utils/TxmaEvent.ts
Updates the lint script so that the PR pipeline fails if there are linting errors
Addresses linting errors.
To catch linting errors in PRs before they are merged
With linting error present
With only warnings present 
- [KIWI-1421](https://govukverify.atlassian.net/browse/KIWI-1421)
[KIWI-1421]: https://govukverify.atlassian.net/browse/KIWI-1421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1421] updates linting script

- Dockerfile
- deploy/template.yaml
- run-tests-locally.sh
- run-tests.sh
- src/package-lock.json
- src/package.json
- src/tests/api/BavHappyPath.test.ts
- src/tests/api/BavUnhappyPath.test.ts
- src/tests/utils/ApiTestSteps.ts
Adds run test scripts
So that we can run the tests in the pipeline
Passing locally 
- [KIWI-1399](https://govukverify.atlassian.net/browse/KIWI-1399)
[KIWI-1399]: https://govukverify.atlassian.net/browse/KIWI-1399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1399 adds test scripts

- infra-l2-outbound-proxy/src/tests/infra/infra.test.ts
- infra-l2-outbound-proxy/template.yaml
Updates proxy to use mock
To use the HMRC mock in dev and build
- [KIWI-1375](https://govukverify.atlassian.net/browse/KIWI-1375)
[KIWI-1375]: https://govukverify.atlassian.net/browse/KIWI-1375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1375: Updates proxy to use HMRC mock

- src/tests/data/exampleStubPayload.json
- src/tests/utils/ApiTestSteps.ts
Update test data to reflect what's built into the Confirmation of Payee Mock service
/verify-account lambda is now pointing to CoP Mock in dev + build and new test data is needed.
- [KIWI-1430](https://govukverify.atlassian.net/browse/KIWI-1430)
[KIWI-1430]: https://govukverify.atlassian.net/browse/KIWI-1430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> QA Updates for CoP Mock

- src/tests/api/BavHappyPath.test.ts
- src/tests/utils/ApiTestSteps.ts
Moved validation of specific vc body fields to the test itself rather than in a generic function. Added validation for the txn field, verifying that it is equal to the hmrcUuid.
- [KIWI-1531](https://govukverify.atlassian.net/browse/KIWI-1531)
[KIWI-1531]: https://govukverify.atlassian.net/browse/KIWI-1531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI 1531 QA

- .secrets.baseline
- src/models/PersonIdentityItem.ts
- src/services/BavService.ts
- src/tests/unit/services/BavService.test.ts
- src/utils/Constants.ts
implements obfuscateJSONValues and logs events sent to TxMA
To help production debugging
- [KIWI-1524](https://govukverify.atlassian.net/browse/KIWI-1524
[KIWI-1524]: https://govukverify.atlassian.net/browse/KIWI-1524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1524: implements obfuscateJSONValues

- src/models/ISessionItem.ts
- src/services/SessionRequestProcessor.ts
- src/services/UserInfoRequestProcessor.ts
- src/tests/api/BavHappyPath.test.ts
- src/tests/unit/services/AbortRequestProcessor.test.ts
- src/tests/unit/services/AccessTokenRequestProcessor.test.ts
- src/tests/unit/services/AuthorizationRequestProcessor.test.ts
- src/tests/unit/services/UserInfoRequestProcessor.test.ts
- src/tests/unit/services/VerifiableCredentialService.test.ts
- src/tests/unit/services/VerifyAccountRequestProcessor.test.ts
- src/utils/Constants.ts
- Reduce max retries to 1 - to allow one attempt and one retry
- Removes `attemptCount` as it has been replaced by `retryCount` and isn't being used
Requirement was incorrectly implemented
First attempt fails
First retry fails
- [KIWI-1416](https://govukverify.atlassian.net/browse/KIWI-1416)
[KIWI-1416]: https://govukverify.atlassian.net/browse/KIWI-1416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Allow one attempt and one retry

- src/services/HmrcService.ts
- src/tests/unit/services/HmrcService.test.ts
error log was displaying the error object which may contain clientId 
Evidence attached to the ticket for reference.
Identified as part of recent incident. 
- [KIWI-1564](https://govukverify.atlassian.net/browse/KIWI-1564)
[KIWI-1564]: https://govukverify.atlassian.net/browse/KIWI-1564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1564]Remove the error object from the error log when HMRCToken endpoint errors out

- deploy/template.yaml
[Updating HMRC URLs to point to Imposter](https://github.com/govuk-one-login/ipv-cri-bav-api/commit/fd3357acbfe163797403e4a444dc790a196f1754)
> [Kiwi 1562] - Updating HMRC URLs to point to Imposter

- run-tests.sh
- src/check-logs.sh
- src/package.json
Adds check-logs script that scans logs for PII that is used in automation testing
To catch PII in our dev deploy workflows
When PII is present
When PII is not present
- [KIWI-1674](https://govukverify.atlassian.net/browse/KIWI-1674)
[KIWI-1674]: https://govukverify.atlassian.net/browse/KIWI-1674?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1674: pii check automation

- deploy/template.yaml
- test-harness/template.yaml
- Add CSLS subscription filter for the spunk onboarding. 
- Modified CSLS Egress stub 2
- Enabled the CSLS filter subscription as splunk onboarding started
- BAV Accounts are added on the CSLS accounts which allows to push log groups
- For onboarding BAV CRI logs into splunk
- [KIWI-1308](https://govukverify.atlassian.net/browse/KIWI-1308)
[KIWI-1308]: https://govukverify.atlassian.net/browse/KIWI-1308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1308: Add CSLS subscription filter for Splunk onboarding

- src/tests/utils/ApiTestSteps.ts
Fix for [KIWI-1590](https://govukverify.atlassian.net/browse/KIWI-1590)
Added new line to include missing import, this is causing api tests to fail in the pipeline
[KIWI-1590]: https://govukverify.atlassian.net/browse/KIWI-1590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1590] - Add missing import to ApiTestSteps

- src/tests/api/ApiTestSteps.ts
- src/tests/api/BavHappyPath.test.ts
- src/tests/api/BavUnhappyPath.test.ts
- src/tests/data/bankDetailsYes.json
Update test data to reflect CoP imposter config updates in [ipv-third-party-stubs Pull Request](https://github.com/govuk-one-login/ipv-third-party-stubs/pull/186)
Support integration testing and allow users to trigger different journeys using accountNumber as opposed to name_parts
- [KIWI-1700](https://govukverify.atlassian.net/browse/KIWI-1700)
[KIWI-1700]: https://govukverify.atlassian.net/browse/KIWI-1700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BAV BE Updates to reflect imposter mock changes

- src/services/SessionRequestProcessor.ts
Move govuk-signin-journey-id to Logger Context earlier as soon the jwt is decoded.
prod errors not capturing the journey-id earlier hence issues with missing info in shared_claims are being missed
- [KIWI-1692](https://govukverify.atlassian.net/browse/KIWI-1692)
[KIWI-1692]: https://govukverify.atlassian.net/browse/KIWI-1692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1692]Move govuk-signin-journey-id to Logger Context earlier

- src/tests/data/BAV_COP_REQUEST_SENT_SCHEMA.json
- src/tests/data/BAV_COP_RESPONSE_RECEIVED_SCHEMA.json
- src/tests/data/BAV_CRI_END_SCHEMA.json
- src/tests/data/BAV_CRI_SESSION_ABORTED_SCHEMA.json
- src/tests/data/BAV_CRI_START_SCHEMA.json
- src/tests/data/BAV_CRI_VC_ISSUED_SCHEMA.json
Test results: 
BE Stack: bav-cri-api-1738
Update JSON Schema for BAV TxMA Validation following the introduction of restricted.device_information.encoded field
- [KIWI-1738](https://govukverify.atlassian.net/browse/KIWI-1738)
[KIWI-1738]: https://govukverify.atlassian.net/browse/KIWI-1738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Kiwi 1738 QA - Update JSON Schema for BAV TxMA Validation

- src/services/SessionRequestProcessor.ts
- src/tests/unit/services/SessionRequestProcessor.test.ts
- Adds null check for headers in session processor
- Small refactor because sonar was complaining about function complexiyy
- Improves test coverage
For testing with API gateway where optional headers are not included
- [KIWI-1796](https://govukverify.atlassian.net/browse/KIWI-1796)
[KIWI-1796]: https://govukverify.atlassian.net/browse/KIWI-1796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1796: adds null check for headers

- deploy/template.yaml
Adding Athena query to the Cloudformation template which can be viewed as Saved queries for our Workspace and one can simply run the query to view the result.
Confluence [page](https://govukverify.atlassian.net/wiki/spaces/BAC/pages/4169924716/How+to+list+Partial+Names+in+Athena) has been updated with the steps to view the Saved queries and run it to view the results.
Enhancement requirement
- [KIWI-1841](https://govukverify.atlassian.net/browse/KIWI-1841)
Evidence of the same attached for ref;
https://github.com/govuk-one-login/ipv-cri-bav-api/assets/115095929/46d6eada-b353-4b81-b6f2-09681984cc97
[KIWI-1841]: https://govukverify.atlassian.net/browse/KIWI-1841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1841] Add Athena queries to the Cloudformation template

- test-harness/test-harness-spec.yaml
Add new endpoint to Test Harness Spec
- getSessionByState
Support E2E testing of abort logic - state value exposed in FE abort journey but not authorizationCode
New endpoint needed to get session data using state
- [KIWI-1863](https://govukverify.atlassian.net/browse/KIWI-1863)
[KIWI-1863]: https://govukverify.atlassian.net/browse/KIWI-1863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1863: Update Test Harness Spec - /getSessionByState endpoint

- src/tests/infra/template.test.ts
Refactored alarm tests, moved to infra tests so we're validating the alarms config in the template.yml 
Checks for the presence of the following fields in all alarms: 
- AlarmName
- Metrics if TreatMissingData is not 'notBreaching'
- ComparisonOperator
- Threshold
- EvaluationPeriods
- AlarmActions
- OKActions
- InsufficientDataActions and DatapointsToAlarm if TreatMissingData is not 'notBreaching'
After discussions with Dan Page we agreed that it would be a bit of a challenge to get our local alarms tests to run in a pipeline and also not provide much value. An alternative approach was suggested to validate the alarms config in the template.yml pre-deployment to ensure there are no issues. 
- [KIWI-1910](https://govukverify.atlassian.net/browse/KIWI-1910)
[KIWI-1910]: …
> Add CloudWatch Alarms tests Infra test run

- deploy/template.yaml
Added SSM parameter to specify which service BAV should be pointing to (HMRC or Experian)
- [KIWI-1926](https://govukverify.atlassian.net/browse/KIWI-1926)
[KIWI-1926]: https://govukverify.atlassian.net/browse/KIWI-1926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add env param for BAV

- .github/workflows/pull-request-sonar.yml
- .github/workflows/run-unit-tests.yml
- .github/workflows/scan-repo.yml
- sonar-project.properties
- src/tsconfig.json
Added github actions to run sonar on pushes to main
So that we can effectively monitor Kiwi services
> KIWI-1958: Added sonar reporting to main branch

- deploy/template.yaml
- Add BAV CRI alarms to the pager duty topic. This will publish on the topic when the alarm is triggered and pager duty will be triggered.
- Add BAV CRI alarms to the pager duty topic to publish the topic
- Add BAV CRI alarms to the pager duty topic to publish the topic
- [IPS-1181](https://govukverify.atlassian.net/browse/IPS-1181)
[IPS-1181]: https://govukverify.atlassian.net/browse/IPS-1181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1181: Subscribe BAV CRI alarms to the pager duty topic

- deploy/bav-spec.yaml
[KIWI-1987] Add max length validation to name fields within the API Spec
- Added maxlength validation to the Account Number and Sort Code fields in BAV, ensuring input does not exceed the required length limits.
- Implemented numeric-only validation for the Account Number and Sort Code fields in the BAV API spec, restricting input to numeric characters only.
- Ensured that all validations for these fields match the frontend.
- [KIWI-XXXX](https://govukverify.atlassian.net/browse/KIWI-XXXX)
Uploading invalid_length-sortcode-BAV.mov…
Uploading invalid_chars-sortcode.mov…
[KIWI-1987]: https://govukverify.atlassian.net/browse/KIWI-1987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Kiwi | BE | Add max length validation to name fields within the API Spec

- src/services/ExperianService.ts
- src/tests/unit/services/ExperianService.test.ts
Updating json to remove trailing commas and fixing the formatting
To test alignment against UAT
> KIWI-1960: Removed trailing commas and readded date of birth. Updated surname to match examples in spec

- deploy/template.yaml
Trying to recreated deleted base api mapping
Conditional added for not creating prod resources 
Drift caused by manually deleting api base mapping resource
PR to delete this resource from state
then can add it back
- [KIWI-XXXX](https://govukverify.atlassian.net/browse/KIWI-XXXX)
> BAU - NotCreateProdResource condition created

- src/models/ISessionItem.ts
- src/models/IVeriCredential.ts
- src/services/BavService.ts
- src/services/ExperianService.ts
- src/services/VerifiableCredentialService.ts
- src/services/VerifyAccountRequestProcessor.ts
- src/tests/unit/services/BavService.test.ts
- src/tests/unit/services/ExperianService.test.ts
- src/tests/unit/services/VerifiableCredentialService.test.ts
- src/tests/unit/services/VerifyAccountRequestProcessorExperian.test.ts
- src/utils/LogResponseCode.ts
Added logic to treat STOP requests as a no match.
Refactored scoring logic to remove it from the user info handlers.
Updated tests
Added outcome to the verify response to make this easier to manage in future
To block users who receive a stop from Experian
To allow us to more easily understand and update scoring logic.
> KIWI-2082: Updating to allow STOP responses to be returned as no match

- src/models/ISessionItem.ts
- src/services/VerifiableCredentialService.ts
- src/services/VerifyAccountRequestProcessor.ts
- src/tests/contract/data/session-items.json
- src/tests/unit/services/UserInfoRequestProcessor.test.ts
- src/tests/unit/services/VerifiableCredentialService.test.ts
Removed mapping logic from the credential creation
To make it easier to amend and update mapping logic
> KIWI-2082: Removing ci mapping logic from credential creation

- deploy/template.yaml
Disabled HMRC token lambda from running
Using Experian as our BAV third party service negates the need for the cron job to run
- [KIWI-2071](https://govukverify.atlassian.net/browse/KIWI-2071)
[KIWI-2071]: https://govukverify.atlassian.net/browse/KIWI-2071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-2071] - BAV | BE | Stop HMRC Token Lambda from needlessly running

- deploy/template.yaml
Added the the client config environment variable to the verify function
To enable the test strategy to select a url in the verify function
> KIWI-1978: Added the client config to the verify function so it can be used for selecting the required url

- README.md
- deploy/template.yaml
- Added LambdaCanaryDeployment preference on updated the pipeline
- Added Code Deploy Service role to allow code deploy
- Set LambdaDeploymentPreference to AllAAatOnce
- Updated lambda functions with the canary deployment configurations
- Added additional alarms for Lambda errors and 5xx errors with lower threshold
- Implement Lambda canary deployment for BAV CRI 
- Implement Lambda canary deployment for BAV CRI 
- [KIWI-1098](https://govukverify.atlassian.net/browse/KIWI-1098)
[KIWI-1098]: https://govukverify.atlassian.net/browse/KIWI-1098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1098: Implement Lambda canary deployment for BAV CRI

- deploy/template.yaml
This is moving to central firewall management via FMS 
Added tags to tell FMS to use a custom webACL for this resource
Added tags
to tell FMS to use a custom webACL for this resource
https://govukverify.atlassian.net/browse/IPS-1407
> Update to include a custom FMS policy

- .secrets.baseline
- deploy/template.yaml
- src/services/AccessTokenRequestProcessor.ts
- src/tests/api/ApiTestSteps.ts
- src/tests/api/alarms/BavAlarms.test.ts
- src/tests/api/backend/BavHappyPath.test.ts
- src/tests/api/backend/BavUnhappyPath.test.ts
- src/tests/api/types.ts
- src/tests/unit/data/accessToken-events.ts
- src/tests/unit/services/AccessTokenRequestProcessor.test.ts
- src/type/AccessRequestPayload.ts
- src/utils/AccessTokenRequestValidations.ts
- src/utils/Constants.ts
- Updated /token lambda to check for presence of `client_assertion_type` and `client_assertion` in the request body
- Verify `client_assertion_type` has the correct value as per OpenID connect documentation
- Verify `client_assertion` JWT signature based on key retrieved via `kid` value in the JWT header
To ensure signature verification is in place for requests to this endpoint
- [KIWI-2297](https://govukverify.atlassian.net/browse/KIWI-2297)
[KIWI-2297]: https://govukverify.atlassian.net/browse/KIWI-2297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OAuth | Verify requests made to /token using Key ID
